//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormItem
    {
        public int FormItemsId { get; set; }
        public string ItemCode { get; set; }
        public string ItemDesc { get; set; }
        public double Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string Currency { get; set; }
        public System.DateTime ROS_Date { get; set; }
        public string Comments { get; set; }
        public int MSRId { get; set; }
        public string AC_No { get; set; }
    
        public virtual ActivityCode ActivityCode { get; set; }
        public virtual MSR MSR { get; set; }
    }
}
