//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSR_MaxEntities : DbContext
    {
        public MSR_MaxEntities()
            : base("name=MSR_MaxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityCode> ActivityCodes { get; set; }
        public virtual DbSet<BudgetInfo> BudgetInfoes { get; set; }
        public virtual DbSet<BudgetPool> BudgetPools { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<FormItem> FormItems { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<MSR> MSRs { get; set; }
        public virtual DbSet<StockItem> StockItems { get; set; }
        public virtual DbSet<Usr> Usrs { get; set; }
        public virtual DbSet<V_Approver_BP> V_Approver_BP { get; set; }
        public virtual DbSet<V_BP_AC_DEPT> V_BP_AC_DEPT { get; set; }
        public virtual DbSet<V_ShowMSR> V_ShowMSR { get; set; }
        public virtual DbSet<V_StockItem_BudgetInfo> V_StockItem_BudgetInfo { get; set; }
    }
}
