//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItem
    {
        public string ItemCode { get; set; }
        public string ItemDesc { get; set; }
        public string LookUp { get; set; }
        public string BarCode { get; set; }
        public string AC_No { get; set; }
        public string Unit { get; set; }
        public bool ActiveFlag { get; set; }
    }
}
