//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_BH_BI
    {
        public int UserId { get; set; }
        public string Username { get; set; }
        public string BP_No { get; set; }
        public string AC_No { get; set; }
    }
}
