//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSR
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ShowMSR
    {
        public int MSRId { get; set; }
        public string BP_No { get; set; }
        public string DeptName { get; set; }
        public string Originator { get; set; }
        public string Approver { get; set; }
        public System.DateTime Req_Date { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> Appr_Date { get; set; }
        public int DeptId_Og { get; set; }
        public int DeptId_Ap { get; set; }
        public string StateFlag { get; set; }
    }
}
